- hosts: san_eng_zone_seed_san_a
  gather_facts: False
  collections: 
   - brocade.fos
  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"
    aliases:
      - name: STG-CB-RT
        members:
          - 50:05:07:68:0d:06:62:50
      - name: STG-CB-LT
        members:
          - 50:05:07:68:0d:06:62:51      
      - name: TIB-KVM-01-P0
        members:
          - 10:00:00:10:9b:e9:d8:21
      - name: TIB-KVM-02-P0
        members:
          - 10:00:00:10:9b:e9:db:f6
            # aliases_to_delete:
            #     - name: Target1
            #    - name: Target2
            # - name: Target3
    zones:
      - name: STG-CB-RT-TIB-KVM-01-P0
        members:
          - STG-CB-RT
          - TIB-KVM-01-P0
          
      - name: STG-CB-LT-TIB-KVM-01-P0
        members:
          - STG-CB-LT
          - TIB-KVM-01-P0
      - name: STG-CB-RT-TIB-KVM-02-P0
        members:
          -  STG-CB-RT   
          -  TIB-KVM-02-P0
      - name: STG-CB-LT-TIB-KVM-02-P0
        members:
          - STG-CB-LT
          - TIB-KVM-02-P0

            #   zones_to_delete:
            #  - name: NewZoneNameP
            # - name: NewZoneName2
    cfgs:
      - name: DC-CB-CFG
        members:
          - STG-CB-RT-TIB-KVM-01-P0
          - STG-CB-LT-TIB-KVM-01-P0
          - STG-CB-RT-TIB-KVM-02-P0
          - STG-CB-LT-TIB-KVM-02-P0  
            #- name: newcfg2
            #members:
            #- NewZoneName
            #- NewZoneName2
            #- name: newcfg3
            #members:
            # - NewZoneName
            #- NewZoneName2
            #cfgs_to_delete:
            #- name: newcfg2
            #- name: newcfg3

           


  tasks:

  - name: Create aliases
    brocade_zoning_alias:
      credential: "{{credential}}"
      vfid: -1
      aliases: "{{aliases}}"
#      aliases_to_delete: "{{aliases_to_delete}}"

  - name: Create zones
    brocade_zoning_zone:
      credential: "{{credential}}"
      vfid: -1
      zones: "{{zones}}"
      #zones_to_delete: "{{zones_to_delete}}"

  - name: Create cfgs
    brocade_zoning_cfg:
      credential: "{{credential}}"
      vfid: -1
      cfgs: "{{cfgs}}"
#      cfgs_to_delete: "{{cfgs_to_delete}}"
      active_cfg: DC-CB-CFG

  - name: Default zoning
    brocade_zoning_default_zone:
      credential: "{{credential}}"
      vfid: -1
      default_zone_access: allaccess
  
